### PR TITLE
add support for column 27: E_we-E_ce/V (fix #74)

### LINKED ISSUE #74: Error when opening *mpr file: 'NotImplementedError: Column ID 27 after column control/mA is unknown'
I'm trying to open .mpr files using the galvani library.
When opening files of GCPL technique of BioLogic, everything is fine.
However, when opening files after the GCPL2 technique, I got error:

NotImplementedError: Column ID 27 after column control/mA is unknown

Looks like this file has some extra, unexpected column.
Is there a way to make this column recognizable and be able to read the file with Galvani?

### PR DESCRIPTION
**Pull request by ilka-schulz**
adds support for column with `id=27`

The column holds a value name `E_we - E_ce` described as `WE versus CE potential` in the manual.

### CODE REVIEW

**Comment by ilka-schulz** [comment]
Example files: https://github.com/echemdata/galvani/issues/74#issuecomment-1297160743

**Comment by ilka-schulz** [comment]
Oh, wait a moment with merging. I will add a test file.

**Comment by ilka-schulz** [comment]
@chatcannon feel free to merge

**Comment by chatcannon** [comment]
The test file should be added as a git-lfs file, not directly to the git repo - see  my comment on #79

**Comment by chatcannon** [comment]
You probably also want to add SPDX metadata for the test data file using a `*.license` file.

**Comment by chatcannon** [comment]
Clearly @ilka-schulz has no intention of making the changes I asked for. I will try doing it myself.

**Comment by chatcannon** [comment]
superseded by #98

**Pull request closed without merging**
