### PR TITLE
Add REUSE metadata

### LINKED ISSUE #34: Add SPDX / fsfe-reuse metadata
Add machine-readable copyright and licensing metadata.

https://reuse.software/

https://github.com/fsfe/reuse-docs/

### PR DESCRIPTION
**Pull request by chatcannon**
Fixes #34

### CODE REVIEW

**Review by bcolsen — APPROVED** [review]
Looks good to me. It doesn't look like the test CI test is competing however.

**Comment by chatcannon** [comment]
It seems like Travis is moving from travis-ci.org to travis-ci.com and this means that previously configured CI pipelines got disabled.

**Comment by chatcannon** [comment]
It looks like the Travis CI build is now running: https://github.com/echemdata/galvani/pull/61/checks?check_run_id=2432514444

**Comment by chatcannon** [comment]
The travis-ci.com checks appeared as a separate item in the "Pull request checks" list - the old travis-ci.org checks were still there and still marked as "waiting". I had to change the "Require status checks to pass before merging" configuration here: https://github.com/echemdata/galvani/settings/branch_protection_rules/5300725

**Pull request merged**
