### PR TITLE
Add '%m.%d.%y' date format for .mpr file timestamps

### LINKED ISSUE #60: [MPR File] ValueError: time data 'XX.XX.XX' does not match format '%m-%d-%y'
Hi, I tried using Galvani for the first time and when trying to load the mpr file from a BioLogic potentiostat, it raises the following exception:

```
ValueError: time data '11.12.20' does not match format '%m/%d/%y'
ValueError: time data '11.12.20' does not match format '%m-%d-%y'
```

It seems like my date format uses dots instead of "/" or "-". Don't know if it has to do with my EC-Labs settings or maybe that the date format of the OS is set to using "." (which is the standard for German date format).

I changed lines 398ff. in "BioLogic.py" to 

```
try:
  tm = time.strptime(settings_mod['date'].decode('ascii'), '%m/%d/%y')
except ValueError:
  try:
      tm = time.strptime(settings_mod['date'].decode('ascii'), '%m-%d-%y')
  except ValueError:
      tm = time.strptime(settings_mod['date'].decode('ascii'), '%m.%d.%y')
```
 
and the same for the similar lines 418ff. which solved the problem. Maybe you want to integrate the additional date format in Galvani, @chatcannon. 

BTW: Thanks a lot for this really nice python package! :)

### PR DESCRIPTION
**Pull request by chatcannon**
Closes #60

### CODE REVIEW

**Comment by chatcannon** [comment]
@regcs Could you test this and see if it works with your files?

**Comment by regcs** [comment]
@chatcannon Unfortunately, it still fails with a ValueError:

```
Traceback (most recent call last):
  File "2021-03-18 CV Auswertung - Figure 1.py", line 116, in <module>
    data_inkjet = read_mpr(file_inkjet, columns=headers, dtypes=dtypes)
  File "2021-03-18 CV Auswertung - Figure 1.py", line 47, in read_mpr
    file = BioLogic.MPRfile(mpr_file)
  File "/opt/anaconda3/lib/python3.8/site-packages/galvani/BioLogic.py", line 404, in __init__
    tm = time.strptime(settings_mod['date'].decode('ascii'), '%m-%d-%y')
  File "/opt/anaconda3/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/opt/anaconda3/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '11.12.20' does not match format '%m-%d-%y'
```

**Comment by chatcannon** [comment]
I see, there are two places with the different time formats but I have only changed one.

**Comment by chatcannon** [comment]
Try the new version and see if that works.

**Comment by chatcannon** [comment]
@regcs Any update? If you have no objections then I will merge this and push a new release to PyPI.

**Comment by regcs** [comment]
@chatcannon Sorry, I missed that. Looks good to me, thanks!

**Pull request merged**
